name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Publish for ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bh-cleanup-app
            asset_name: bh-cleanup-app-linux-amd64
          - os: macos-latest
            artifact_name: bh-cleanup-app
            asset_name: bh-cleanup-app-macos
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bh-cleanup-app
        path: /home/runner/work/bh-cleanup-app/
